version: "3.8"

services:
  backend:
    image: yuthikavj31545/mern-backend:latest
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: ${MONGO_URI}

  frontend:
    image: yuthikavj31545/mern-frontend:latest
    ports:
      - "80:80"
    environment:
      REACT_APP_END_POINT: http://${EC2_HOST}:5000
    depends_on:
      - backend
    restart: always

