name : Mern CI/CD Pipeline

on:
    push:
        branches: ["main"]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME}}
                password: ${{ secrets.DOCKER_PASSWORD}}

            - name: Build and Push Backend Image
              run: |
                docker buildx build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/mern-backend:latest --push ./backend
            
            - name: Build and Push Frontend Image
              run: |
                docker buildx build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/mern-frontend:latest --push ./frontend
            
            - name: Deploy to EC2
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.EC2_HOST}}
                username: ${{ secrets.EC2_USER}}
                key: ${{ secrets.EC2_KEY}}
                script: |
                  docker pull ${{ secrets.DOCKER_USERNAME}}/mern-backend:latest
                  docker pull ${{ secrets.DOCKER_USERNAME}}/mern-frontend:latest

                  export MONGO_URI="${{ secrets.MONGO_URI }}"

                  docker-compose down
                  docker-compose up -d